version: '2'

services:
  nginx:
    # Force docker-compose to use a comprehensive name for the image
    image: bitnami_nginx:1.14-rhel-7
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '80:8080'
    environment:
      - NGINX_HTTP_PORT_NUMBER=8080
